[package]
org = "xlibb"
name = "asb"
version = "@toml.version@"
authors = ["xlibb"]
keywords = ["asb"]
repository = "https://github.com/xlibb/module-asb"
license = ["Apache-2.0"]
distribution = "2201.3.0"
icon = "icon.png"

[[platform.java11.dependency]]
groupId = "io.xlibb"
artifactId = "asb-native"
version = "@toml.version@"
path = "../native/build/libs/asb-native-@project.version@.jar"

# Azure dependencies
[[platform.java11.dependency]]
groupId = "com.azure"
artifactId = "azure-messaging-servicebus"
version = "@asb.version@"
path = "./lib/azure-messaging-servicebus-@asb.version@.jar"

[[platform.java11.dependency]]
groupId = "com.azure"
artifactId = "azure-core"
version = "@azure.core.version@"
path = "./lib/azure-core-@azure.core.version@.jar"

[[platform.java11.dependency]]
groupId = "com.azure"
artifactId = "azure-core-amqp"
version = "@azure.core.amqp.version@"
path = "./lib/azure-core-amqp-@azure.core.amqp.version@.jar"

[[platform.java11.dependency]]
groupId = "com.azure"
artifactId = "azure-core-http-netty"
version = "@azure.core.http.netty.version@"
path = "./lib/azure-core-http-netty-@azure.core.http.netty.version@.jar"

# Jackson dependencies
[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-annotations"
version = "2.13.4"
path = "./lib/jackson-annotations-2.13.4.jar"

[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-core"
version = "2.13.4"
path = "./lib/jackson-core-2.13.4.jar"

[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-databind"
version = "2.13.4.2"
path = "./lib/jackson-databind-2.13.4.2.jar"

[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.datatype"
artifactId = "jackson-datatype-jsr310"
version = "2.13.4"
path = "./lib/jackson-datatype-jsr310-2.13.4.jar"

[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.dataformat"
artifactId = "jackson-dataformat-xml"
version = "2.13.4"
path = "./lib/jackson-dataformat-xml-2.13.4.jar"

# Netty dependencies
[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-buffer"
version = "@netty.version@"
path = "./lib/netty-buffer-@netty.version@.jar"


[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-codec"
version = "@netty.version@"
path = "./lib/netty-codec-@netty.version@.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-codec-dns"
version = "@netty.version@"
path = "./lib/netty-codec-dns-@netty.version@.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-codec-http"
version = "@netty.version@"
path = "./lib/netty-codec-http-@netty.version@.jar"


[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-codec-http2"
version = "@netty.version@"
path = "./lib/netty-codec-http2-@netty.version@.jar"


[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-codec-socks"
version = "@netty.version@"
path = "./lib/netty-codec-socks-@netty.version@.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-common"
version = "@netty.version@"
path = "./lib/netty-common-@netty.version@.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-handler"
version = "@netty.version@"
path = "./lib/netty-handler-@netty.version@.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-handler-proxy"
version = "@netty.version@"
path = "./lib/netty-handler-proxy-@netty.version@.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-resolver"
version = "@netty.version@"
path = "./lib/netty-resolver-@netty.version@.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-resolver-dns"
version = "@netty.version@"
path = "./lib/netty-resolver-dns-@netty.version@.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-resolver-dns-classes-macos"
version = "@netty.version@"
path = "./lib/netty-resolver-dns-classes-macos-@netty.version@.jar"

[[platform.java11.dependency]]
path = "./lib/netty-resolver-dns-native-macos-@netty.version@-osx-x86_64.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-transport"
version = "@netty.version@"
path = "./lib/netty-transport-@netty.version@.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-transport-classes-epoll"
version = "@netty.version@"
path = "./lib/netty-transport-classes-epoll-@netty.version@.jar"

[[platform.java11.dependency]]
path = "./lib/netty-transport-native-epoll-@netty.version@-linux-x86_64.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-transport-classes-kqueue"
version = "@netty.version@"
path = "./lib/netty-transport-classes-kqueue-@netty.version@.jar"

[[platform.java11.dependency]]
path = "./lib/netty-transport-native-kqueue-@netty.version@-osx-x86_64.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-transport-native-unix-common"
version = "@netty.version@"
path = "./lib/netty-transport-native-unix-common-@netty.version@.jar"

# Netty tcnative dependencies
[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-tcnative-classes"
version = "@netty.tcnative.version@"
path = "./lib/netty-tcnative-classes-@netty.tcnative.version@.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-tcnative-boringssl-static"
version = "@netty.tcnative.version@"
path = "./lib/netty-tcnative-boringssl-static-@netty.tcnative.version@.jar"

[[platform.java11.dependency]]
path = "./lib/netty-tcnative-boringssl-static-@netty.tcnative.version@-windows-x86_64.jar"

[[platform.java11.dependency]]
path = "./lib/netty-tcnative-boringssl-static-@netty.tcnative.version@-linux-aarch_64.jar"

[[platform.java11.dependency]]
path = "./lib/netty-tcnative-boringssl-static-@netty.tcnative.version@-linux-x86_64.jar"

[[platform.java11.dependency]]
path = "./lib/netty-tcnative-boringssl-static-@netty.tcnative.version@-osx-aarch_64.jar"

[[platform.java11.dependency]]
path = "./lib/netty-tcnative-boringssl-static-@netty.tcnative.version@-osx-x86_64.jar"

# Project reactor dependencies
[[platform.java11.dependency]]
groupId = "io.projectreactor"
artifactId = "reactor-core"
version = "3.4.23"
path = "./lib/reactor-core-3.4.23.jar"

[[platform.java11.dependency]]
groupId = "io.projectreactor.netty"
artifactId = "reactor-netty-core"
version = "1.0.23"
path = "./lib/reactor-netty-core-1.0.23.jar"

[[platform.java11.dependency]]
groupId = "io.projectreactor.netty"
artifactId = "reactor-netty-http"
version = "1.0.23"
path = "./lib/reactor-netty-http-1.0.23.jar"

# Apache proton-j dependencies
[[platform.java11.dependency]]
groupId = "org.apache.qpid"
artifactId = "proton-j"
version = "0.33.8"
path = "./lib/proton-j-0.33.8.jar"

# Reactive streams dependencies
[[platform.java11.dependency]]
groupId = "org.reactivestreams"
artifactId = "reactive-streams"
version = "1.0.4"
path = "./lib/reactive-streams-1.0.4.jar"
