[package]
org = "xlibb"
name = "asb"
version = "0.1.0"
authors = ["xlibb"]
keywords = ["asb"]
repository = "https://github.com/xlibb/module-asb"
license = ["Apache-2.0"]
distribution = "2201.3.0"
icon = "icon.png"

[[platform.java11.dependency]]
groupId = "io.xlibb"
artifactId = "asb-native"
version = "0.1.0"
path = "../native/build/libs/asb-native-0.1.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
groupId = "com.azure"
artifactId = "azure-messaging-servicebus"
version = "7.13.0"
path = "./lib/azure-messaging-servicebus-7.13.0.jar"

[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-annotations"
version = "2.13.4"
path = "./lib/jackson-annotations-2.13.4.jar"

[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-core"
version = "2.13.4"
path = "./lib/jackson-core-2.13.4.jar"

[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-databind"
version = "2.13.4.2"
path = "./lib/jackson-databind-2.13.4.2.jar"

[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.datatype"
artifactId = "jackson-datatype-jsr310"
version = "2.13.4"
path = "./lib/jackson-datatype-jsr310-2.13.4.jar"

[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.dataformat"
artifactId = "jackson-dataformat-xml"
version = "2.13.4"
path = "./lib/jackson-dataformat-xml-2.13.4.jar"

[[platform.java11.dependency]]
groupId = "com.fasterxml.woodstox"
artifactId = "woodstox-core"
version = "6.4.0"
path = "./lib/woodstox-core-6.4.0.jar"
