[package]
org = "xlibb"
name = "asb"
version = "0.1.0"
authors = ["xlibb"]
keywords = ["asb"]
repository = "https://github.com/xlibb/module-asb"
license = ["Apache-2.0"]
distribution = "2201.3.0"
icon = "icon.png"

[[platform.java11.dependency]]
groupId = "io.xlibb"
artifactId = "asb-native"
version = "0.1.0"
path = "../native/build/libs/asb-native-0.1.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/azure-messaging-servicebus-7.13.0.jar"

[[platform.java11.dependency]]
path = "./lib/azure-core-1.34.0.jar"

[[platform.java11.dependency]]
path = "./lib/azure-core-amqp-2.8.0.jar"

[[platform.java11.dependency]]
path = "./lib/azure-core-http-netty-1.12.7.jar"

[[platform.java11.dependency]]
path = "./lib/jackson-dataformat-xml-2.13.4.jar"

[[platform.java11.dependency]]
path = "./lib/reactive-streams-1.0.4.jar"

[[platform.java11.dependency]]
path = "./lib/jackson-core-2.13.4.jar"

[[platform.java11.dependency]]
path = "./lib/jackson-databind-2.13.4.2.jar"

[[platform.java11.dependency]]
path = "./lib/jackson-datatype-jsr310-2.13.4.jar"

[[platform.java11.dependency]]
path = "./lib/jackson-annotations-2.13.4.jar"

[[platform.java11.dependency]]
path = "./lib/proton-j-0.33.8.jar"

[[platform.java11.dependency]]
path = "./lib/netty-common-4.1.82.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-buffer-4.1.82.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-transport-4.1.82.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-resolver-4.1.82.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-handler-4.1.82.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-http-4.1.82.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-4.1.82.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-handler-proxy-4.1.82.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-http2-4.1.82.Final.jar"

[[platform.java11.dependency]]
path = "./lib/reactor-netty-http-1.0.23.jar"
